
---
- name: Install Kubernetes
  hosts: mycomp
  become: yes

  roles:
    - role: pretask
      tags:
        - pretask
  

    - role: containerd
      tags:
        - installcontainerd

    - role: instkube
      tags:
        - installkubernetes

    - role: insthelm
      tags:
        - installhelm


