
---
- name: Install Kubernetes
  hosts: mycomp
  become: yes

  roles:
    - role: pretask
      tags:
        - pretask
  

    - role: containerd
      tags:
        - containerd

    - role: instkube
      tags:
        - kubeadm

    - role: insthelm
      tags:
        - helm


