---
- name: Checking br_netfilter loaded
  command: lsmod | grep br_netfilter
  register: br_netfilter_status
  changed_when: false
  ignore_errors: yes

- name: Log br_netfilter status
  debug:
    msg: "br_netfilter loaded: {{ br_netfilter_status.stdout != '' }}"

- name: Load br_netfilter
  command: modprobe br_netfilter
  when: br_netfilter_status.failed

- name: Configure kernel module loading
  copy:
    dest: /etc/modules-load.d/k8s.conf
    content: |
      br_netfilter
  register: module_config
  changed_when: module_config.changed

- name: Configure sysctl settings
  copy:
    dest: /etc/sysctl.d/k8s.conf
    content: |
      net.bridge.bridge-nf-call-iptables = 1
      net.bridge.bridge-nf-call-ip6tables = 1
      net.ipv4.ip_forward = 1
  register: sysctl_config
  changed_when: sysctl_config.changed

- name: Apply sysctl settings
  command: sysctl --system
  register: sysctl_status

- name: Log sysctl settings
  debug:
    msg: "Sysctl settings applied: {{ sysctl_status.stdout }}"
  when: sysctl_status.changed

